/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Tur2RouteImport } from './routes/tur2'
import { Route as SonuclarRouteImport } from './routes/sonuclar'
import { Route as MilletvekiliRouteImport } from './routes/milletvekili'
import { Route as HaritaRouteImport } from './routes/harita'
import { Route as AnketlerRouteImport } from './routes/anketler'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RehberIndexRouteImport } from './routes/rehber.index'
import { Route as HaberlerIndexRouteImport } from './routes/haberler.index'
import { Route as RehberSlugRouteImport } from './routes/rehber.$slug'
import { Route as IlIdRouteImport } from './routes/il.$id'
import { Route as HaberlerIdRouteImport } from './routes/haberler.$id'

const Tur2Route = Tur2RouteImport.update({
  id: '/tur2',
  path: '/tur2',
  getParentRoute: () => rootRouteImport,
} as any)
const SonuclarRoute = SonuclarRouteImport.update({
  id: '/sonuclar',
  path: '/sonuclar',
  getParentRoute: () => rootRouteImport,
} as any)
const MilletvekiliRoute = MilletvekiliRouteImport.update({
  id: '/milletvekili',
  path: '/milletvekili',
  getParentRoute: () => rootRouteImport,
} as any)
const HaritaRoute = HaritaRouteImport.update({
  id: '/harita',
  path: '/harita',
  getParentRoute: () => rootRouteImport,
} as any)
const AnketlerRoute = AnketlerRouteImport.update({
  id: '/anketler',
  path: '/anketler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberIndexRoute = RehberIndexRouteImport.update({
  id: '/rehber/',
  path: '/rehber/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerIndexRoute = HaberlerIndexRouteImport.update({
  id: '/haberler/',
  path: '/haberler/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberSlugRoute = RehberSlugRouteImport.update({
  id: '/rehber/$slug',
  path: '/rehber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IlIdRoute = IlIdRouteImport.update({
  id: '/il/$id',
  path: '/il/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerIdRoute = HaberlerIdRouteImport.update({
  id: '/haberler/$id',
  path: '/haberler/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anketler': typeof AnketlerRoute
  '/harita': typeof HaritaRoute
  '/milletvekili': typeof MilletvekiliRoute
  '/sonuclar': typeof SonuclarRoute
  '/tur2': typeof Tur2Route
  '/haberler/$id': typeof HaberlerIdRoute
  '/il/$id': typeof IlIdRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/rehber/': typeof RehberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anketler': typeof AnketlerRoute
  '/harita': typeof HaritaRoute
  '/milletvekili': typeof MilletvekiliRoute
  '/sonuclar': typeof SonuclarRoute
  '/tur2': typeof Tur2Route
  '/haberler/$id': typeof HaberlerIdRoute
  '/il/$id': typeof IlIdRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/haberler': typeof HaberlerIndexRoute
  '/rehber': typeof RehberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anketler': typeof AnketlerRoute
  '/harita': typeof HaritaRoute
  '/milletvekili': typeof MilletvekiliRoute
  '/sonuclar': typeof SonuclarRoute
  '/tur2': typeof Tur2Route
  '/haberler/$id': typeof HaberlerIdRoute
  '/il/$id': typeof IlIdRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/rehber/': typeof RehberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anketler'
    | '/harita'
    | '/milletvekili'
    | '/sonuclar'
    | '/tur2'
    | '/haberler/$id'
    | '/il/$id'
    | '/rehber/$slug'
    | '/haberler/'
    | '/rehber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anketler'
    | '/harita'
    | '/milletvekili'
    | '/sonuclar'
    | '/tur2'
    | '/haberler/$id'
    | '/il/$id'
    | '/rehber/$slug'
    | '/haberler'
    | '/rehber'
  id:
    | '__root__'
    | '/'
    | '/anketler'
    | '/harita'
    | '/milletvekili'
    | '/sonuclar'
    | '/tur2'
    | '/haberler/$id'
    | '/il/$id'
    | '/rehber/$slug'
    | '/haberler/'
    | '/rehber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnketlerRoute: typeof AnketlerRoute
  HaritaRoute: typeof HaritaRoute
  MilletvekiliRoute: typeof MilletvekiliRoute
  SonuclarRoute: typeof SonuclarRoute
  Tur2Route: typeof Tur2Route
  HaberlerIdRoute: typeof HaberlerIdRoute
  IlIdRoute: typeof IlIdRoute
  RehberSlugRoute: typeof RehberSlugRoute
  HaberlerIndexRoute: typeof HaberlerIndexRoute
  RehberIndexRoute: typeof RehberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tur2': {
      id: '/tur2'
      path: '/tur2'
      fullPath: '/tur2'
      preLoaderRoute: typeof Tur2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonuclar': {
      id: '/sonuclar'
      path: '/sonuclar'
      fullPath: '/sonuclar'
      preLoaderRoute: typeof SonuclarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milletvekili': {
      id: '/milletvekili'
      path: '/milletvekili'
      fullPath: '/milletvekili'
      preLoaderRoute: typeof MilletvekiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harita': {
      id: '/harita'
      path: '/harita'
      fullPath: '/harita'
      preLoaderRoute: typeof HaritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anketler': {
      id: '/anketler'
      path: '/anketler'
      fullPath: '/anketler'
      preLoaderRoute: typeof AnketlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/': {
      id: '/rehber/'
      path: '/rehber'
      fullPath: '/rehber/'
      preLoaderRoute: typeof RehberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler/': {
      id: '/haberler/'
      path: '/haberler'
      fullPath: '/haberler/'
      preLoaderRoute: typeof HaberlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/$slug': {
      id: '/rehber/$slug'
      path: '/rehber/$slug'
      fullPath: '/rehber/$slug'
      preLoaderRoute: typeof RehberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il/$id': {
      id: '/il/$id'
      path: '/il/$id'
      fullPath: '/il/$id'
      preLoaderRoute: typeof IlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler/$id': {
      id: '/haberler/$id'
      path: '/haberler/$id'
      fullPath: '/haberler/$id'
      preLoaderRoute: typeof HaberlerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnketlerRoute: AnketlerRoute,
  HaritaRoute: HaritaRoute,
  MilletvekiliRoute: MilletvekiliRoute,
  SonuclarRoute: SonuclarRoute,
  Tur2Route: Tur2Route,
  HaberlerIdRoute: HaberlerIdRoute,
  IlIdRoute: IlIdRoute,
  RehberSlugRoute: RehberSlugRoute,
  HaberlerIndexRoute: HaberlerIndexRoute,
  RehberIndexRoute: RehberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
